project:
  type: book
  output-dir: docs
  preview:
    browser: true

# bootstraping  https://acclab.github.io/dabestr/articles/tutorial_basics.html
# causal inference https://ngreifer.github.io/software/ causal
# fix honest_plots chatbot
# fix clear_plots chatbot

book:
  title: "Applied Biostatistics"
  author: "Yaniv Brandvain"
  date: today
  sidebar:
    search: true
    background: '#3A5F0B' #"#9f86c0"
    logo: "figs/fun_figs/stamp.png"
    collapse-level: 1 # Add this line
  chapters:
    - index.qmd
    - book_sections/clarkia_and_its_data/clarkia_and_its_data.qmd
    - book_sections/example_mini/varType.qmd
    - book_sections/filler.qmd
    - book_sections/intro2r_index.qmd
    - part: book_sections/getting_started.qmd
      chapters: 
        - book_sections/getting_started/Rtips.qmd
        - book_sections/getting_started/functions.qmd
        - book_sections/getting_started/robjects.qmd
        - book_sections/getting_started/assignment.qmd
        - book_sections/getting_started/packages.qmd
        - book_sections/getting_started/Rscripts.qmd
        - book_sections/getting_started/getting_started_summary.qmd
    - part: book_sections/intro_to_ggplot.qmd
      chapters: 
        - book_sections/intro_to_ggplot/one_continuous.qmd
        - book_sections/intro_to_ggplot/saving_ggplots.qmd
        - book_sections/intro_to_ggplot/cont_cat.qmd
        - book_sections/intro_to_ggplot/two_categorical.qmd
        - book_sections/intro_to_ggplot/two_continuous.qmd
        - book_sections/intro_to_ggplot/many_explanatory.qmd
        - book_sections/intro_to_ggplot/ggplot_summary.qmd
    - part: book_sections/reproducible_science.qmd
      chapters: 
        - book_sections/reproducible_science/collecting_data.qmd
        - book_sections/reproducible_science/storing_data.qmd
        - book_sections/reproducible_science/loading_data.qmd
        - book_sections/reproducible_science/check_and_prep.qmd
        - book_sections/reproducible_science/reproducible_analyses.qmd
        - book_sections/reproducible_science/reproducible_summary.qmd  
    - part: book_sections/data_in_R.qmd
      chapters: 
        - book_sections/data_in_R/select_vars.qmd
        - book_sections/data_in_R/add_vars.qmd
        - book_sections/data_in_R/choose_rows.qmd
        - book_sections/data_in_R/dealing_w_data_script.qmd
        - book_sections/data_in_R/data_in_R_summary.qmd
    - part: book_sections/univariate_summaries.qmd
      chapters: 
        - book_sections/univariate_summaries/summarizing_shape.qmd
        - book_sections/univariate_summaries/changing_shape.qmd
        - book_sections/univariate_summaries/summarizing_center.qmd
        - book_sections/univariate_summaries/summarizing_variability.qmd
        - book_sections/univariate_summaries/summary_script.qmd
        - book_sections/univariate_summaries/summarizing_summaries.qmd
    - part: book_sections/associations_I.qmd
      chapters: 
        - book_sections/associations/two_categorical_vars.qmd
        - book_sections/associations/cat_cont.qmd
        - book_sections/associations/associationsI_script.qmd
        - book_sections/associations/summarizing_associations_I.qmd
    - part: book_sections/associations_II.qmd
      chapters: 
        - book_sections/associations/two_categorical_vars_II.qmd
        - book_sections/associations/cont_cont.qmd
        - book_sections/associations/associationsII_script.qmd
        - book_sections/associations/summarizing_associations_II.qmd
    - book_sections/filler.qmd
    - book_sections/stats_foundation_index.qmd
    - part: book_sections/sampling_intro.qmd
      chapters: 
        - book_sections/sampling/sampling.qmd
        - book_sections/sampling/sampling_error.qmd
        - book_sections/sampling/sampling_bias.qmd
        - book_sections/sampling/nonindependence.qmd
        - book_sections/sampling/better_sampling.qmd       
        - book_sections/sampling/sampling_summary.qmd
    - book_sections/filler.qmd
    - book_sections/additional_resources_index.qmd
    - part: book_sections/supps.qmd
      chapters: 
        - book_sections/effect_size_ref.qmd
    - references.qmd


 


bibliography: ["assets/modeling.bib", "assets/packages.bib"]
csl: 'assets/apa-single-spaced.csl'

format:
  html:
    theme: 
      - flatly
      - "assets/theme_corrected.scss"
    css: ["assets/sticky-notes.css", "assets/table-styles.css", "assets/webex.css"]
    include-after-body: assets/webex.js
    code-copy: true
    highlight-style: default
    mainfont: 'Crimson Text'
    fontsize: '14pt'
    linestretch: '1.5em'
    linkcolor: '#20a2a3' 
    toc: false
    link-external-newwindow: true
editor: source
filters:
 - webr
 - shinylive
 
 
resources:
  - widget.html
  - widget-script.js 