install.packages("blogdown")
install.packages("knitr")
install.packages("gt")
install.packages("gtExtras")
install.packages("patchwork")
install.packages("cowplot")
install.packages("devtools")
install.packages("tufte")
install.packages("kableExtra")
install.packages("DT")
install.packages("webexercises")
install.packages("plotly")
install.packages("ggthemes")
install.packages("palmerpenguins")
install.packages("GGally")
install.packages("ggrepel")
install.packages("ggforce")
install.packages("ggfortify")
install.packages("ggeffects")
install.packages("nlme")
install.packages("lme4")
install.packages("lmerTest")
install.packages("FactoMineR")
install.packages("datasauRus")
install.packages("factoextra")
install.packages("highcharter")
install.packages("shinylive")
install.packages("maps")
install.packages("mapproj")
install.packages("munsell")
install.packages("ggimage")
install.packages("ggtext")
install.packages("infer")
install.packages("boot")
install.packages("Hmisc")
install.packages("ggridges")
install.packages("janitor")
install.packages("gganimate")
install.packages("ggExtra")
install.packages("caret")
install.packages("pwr")
install.packages("multcomp")
install.packages("dagitty")
install.packages("ggdag")
install.packages("bslib")
devtools::install_github("gadenbuie/tweetrmd")
devtools::install_github("hadley/emo")
remotes::install_github("gadenbuie/tiktokrmd")
add_to_bookdown(bookdown_dir = ".",
                include_dir = "www",
                script_dir = "scripts",
                output_format = "gitbook")


# In terminal "quarto add coatless/quarto-webr"