# 13. Linear Models {#linear_models}



```{r}
#| echo: false
#| message: false
#| warning: false
library(knitr)
library(dplyr)
library(readr)
library(stringr)
library(DT)
library(webexercises)
library(ggplot2)
library(tidyr)
source("../_common.R") 

ril_link <- "https://raw.githubusercontent.com/ybrandvain/datasets/refs/heads/master/clarkia_rils.csv"
ril_data <- readr::read_csv(ril_link) |>
  dplyr::mutate(growth_rate = case_when(growth_rate =="1.8O" ~ "1.80",
                                          .default = growth_rate),  
                growth_rate = as.numeric(growth_rate),
                visited = mean_visits > 0)
gc_rils <- ril_data |>
  filter(location == "GC", !is.na(prop_hybrid), ! is.na(mean_visits))|>
  select(petal_color, petal_area_mm, num_hybrid, offspring_genotyped, prop_hybrid, mean_visits , asd_mm )
```



::: {.motivation style="background-color: #ffe6f7; padding: 10px; border: 1px solid #ddd; border-radius: 5px;"}

**Motivating Scenario:** 
You want to move beyond simply plotting and summarizing associations and start modeling relationships between variables.    

**Learning Goals: By the end of this chapter, you should be able to:**  

1. **Explain what a linear model is and what it does**.    
   - Understand a linear model as a way of estimating the conditional mean of a response variable.  

2. **Interpret the components of a linear model**    
   - Find a conditional mean, $\hat{Y_i}$, from a linear model.    
   - Define and interpret residuals and the residual standard deviation.   


:::     

---



<article class="drop-cap">Reality is messy. There's too much going on to notice everything at once. That's why we make models — simplified, abstract descriptions of the world — that help us focus on patterns we care about. Models aren't perfect copies of reality — they leave things out — and that's the point. A good model keeps what's important and ignores the rest. In statistics, models help us summarize what we observe, understand relationships,  make predictions, and even allow us to test hypotheses.</br></br></article>


In this section, we'll introduce statistical models as simplified descriptions of the world. You'll notice that you're already familiar with some simple models. For example, the mean and variance provide a basic model for a single numeric variable, while a conditional mean and pooled variance describe a numeric response variable with a categorical explanatory variable. 


### Scientific & statistical models revisited: The *Clarkia* case study

In our *Clarkia* example, the big-picture scientific model is that when *parviflora* came back into contact with its close relative, *xantiana*, it evolved traits — such as smaller petals — to avoid producing hybrids.  No single statistical model or study fully captures this scientific model. Instead, we design experiments to evaluate pieces of the model. For example, we:

1. **Compare petal area** between *parviflora* plants from populations that occur with *xantiana* (sympatric populations) and those from populations far away from *xantiana* (allopatric populations).

2. **Conduct an experiment** by planting individuals from sympatric and allopatric *parviflora* populations in the same environment as *xantiana*, and comparing the amount of hybrid seed set by plants from each origin.

3. **Generate Recombinant Inbred Lines (RILs)** between sympatric and allopatric *parviflora* populations, and examine whether petal area is associated with the proportion of hybrid seeds produced.

As you can see, statistical models don’t "know" anything about biology — they simply describe patterns in data.   It’s up to us, as biologists, to design experiments carefully, choose the right statistical models, and interpret results in light of our biological hypotheses.



## Linear models 

Linear models are among the most common types of statistical model. Linear models estimate the conditional mean of the $i^{th}$ observation, given its predictor values, ($\text{explanatory variables}_i$): 



\begin{equation} 
\hat{Y}_i = f(\text{explanatory variables}_i)
\end{equation} 


:::aside
**Conditional mean:** The expected value of a response variable given specific values of the explanatory variables (i.e., the model’s best guess for the response based on the explanatory variables).  
:::



These models are "linear" because we get this estimate of the conditional mean, $\hat{Y}_i$, by adding up all components of the model. That is, the value of the $j^{th}$ explanatory variable in the $i^{th}$ individual  $x_{j,i}$ is multiplied by its effect size $b_j$.   So, for example, $\hat{Y}_i$ equals the parameter estimate for the "intercept", $a$ plus its value for the first explanatory variable, $x_{1,i}$, times the effect of this variable, $b_1$, plus its value for the second explanatory variable, $x_{2,i}$ times the effect of this variable, $b_2$, and so on for all included predictors.

\begin{equation} 
\hat{Y}_i = a + b_1  x_{1,i} + b_2 x_{2,i} + \dots{}
\end{equation}

To make this more concrete, we may aim to predict the number of pollinator visits of a pink flower with a petal area of 70 $mm^2$. We would find this by starting at some intercept, adding the effect of pink flowers on visitation, and then adding the increase in visitation per $mm^2$ times seventy. 

## Assumptions, Caveats and our limited ambitions 

In this section, we focus on building and interpreting linear models as descriptions of data. 

But, it should leave us well positioned to evaluate the uncertainty in estimates from linear models, test null hypotheses and the like. Because we're just introducing linear models here, we will save the important questions about what makes a linear model reasonable, and evaluate if a model meets its assumptions until later in the book. 




## Let's get started introducing linear models!    

Throughout this chapter we will model a single response variable -- the proportion of hybrids that a mom produced. As you see below, much of this chapter recasts concepts you have already learned in the framework of a linear model. 

- We will start with the simplest linear model -- [the mean](#mean). While we have already [introduced the mean](#summarizing_center), presenting it in the context of a linear model helps us prepare for our next steps!   Specifically, we will use the mean to introduce: 

   - **`R`'s [`lm()`](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/lm.html) function** that builds a linear model, and    
   - **Residuals** -- The difference between an individual data point, $Y_i$, and its value predicted from a linear model, $\hat{Y_i}$. In this section we will also learn how to   
      - Identify residuals on a plot, and 
      - Use the [`augment()`](https://broom.tidymodels.org/reference/augment.lm.html) function from the [`broom`](https://broom.tidymodels.org/reference/augment.lm.html) package to find residuals in R.  

- We will then briefly introduce a few more involved linear models -- including one to model two groups, one  to model a continuous explanatory variable, and a third with a continuous and categorical predictor. The point of these models is to get you ready for what is to come in the following chapters! 


---




:::learnmore
**OPTIONAL / ADVANCED, FOR MATH NERDS:**.  If you have a background in linear algebra, it might help to see a linear model in matrix notation. 

The first matrix below is known as the  *design matrix*. Each row corresponds to an individual, and each entry in the $i$th row corresponds to that individual's value for a given explanatory variable. We take the dot product of this matrix and our estimated parameters to get the predictions for each individual. The equation below has $n$ individuals and $k$ explanatory variables. Note that every individual has a value of 1 for the intercept.


\begin{equation} 
\begin{pmatrix}
    1 & x_{1,1} & x_{2,1} & \dots  & x_{k,1} \\
    1 & x_{1,2} & x_{2,2} & \dots  & x_{k,2} \\
    \vdots & \vdots & \vdots & \ddots & \vdots \\
    1 & x_{1,n} & x_{2,n} & \dots  & x_{k,n}
\end{pmatrix}
\cdot 
\begin{pmatrix}
    a \\
    b_{1}\\
    b_{2}\\
    \vdots  \\
     b_{k}
\end{pmatrix}
=
\begin{pmatrix}
    \hat{Y}_1 \\
    \hat{Y}_2\\
    \vdots  \\
    \hat{Y}_n
\end{pmatrix}
\end{equation}
:::
 
 